:bug: Release G1-G3 from JTAG control
libhal/libhal-micromod pull request #16
Opened 2024-09-22 22:37 UTC by MaliaLabor

This is required to use these pins as GPIO

2024-09-22 22:37 UTC, MaliaLabor commented
@PhazonicRidley Can you pull down this PR and check that this works?

2024-09-22 23:15 UTC, PhazonicRidley commented
Works perfectly! Could you also add it to the v5 profile? Thank you very much!

2024-09-22 23:17 UTC, PhazonicRidley requested changes
Looks good, works after testing. Could you add this change to the v5 stm32 profile as well? Thank you!

2024-09-23 17:17 UTC, kammce approved these changes

2024-09-23 17:17 UTC, merged